# Working WithDummy JSON Data With API

In [3]:
#api endpoints
products_url = 'https://dummyjson.com/products'
carts_url = 'https://dummyjson.com/carts'

## Install the `requests` library

In [4]:
! pip install requests pandas

Requirement already satisfied: requests in /home/urbano/vault/projects/data_science/luxdev/.venv/lib/python3.12/site-packages (2.34.2)
Requirement already satisfied: pandas in /home/urbano/vault/projects/data_science/luxdev/.venv/lib/python3.12/site-packages (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/urbano/vault/projects/data_science/luxdev/.venv/lib/python3.12/site-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /home/urbano/vault/projects/data_science/luxdev/.venv/lib/python3.12/site-packages (from requests) (3.17)
Requirement already satisfied: urllib3<3,>=1.26 in /home/urbano/vault/projects/data_science/luxdev/.venv/lib/python3.12/site-packages (from requests) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in /home/urbano/vault/projects/data_science/luxdev/.venv/lib/python3.12/site-packages (from requests) (2026.5.20)
Requirement already satisfied: numpy>=1.26.0 in /home/urbano/vault/projects/data_science/luxdev/.venv/lib/python3.12/site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/urbano/vault/projects/data_science/luxdev/.venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/urbano/vault/projects/data_science/luxdev/.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [5]:
#import requests
import requests
import pandas as pd

### Retrieve both products and cart data in clean flat tables

After retrieving data, I use .json_normalize so that nested dictionaries inside columns are extracted into own separate columns.

In [6]:
get_products_data = requests.get(products_url)

if get_products_data.status_code == 200:
    #parse json data into a dictionary or list
    products_data = get_products_data.json()
    print("Products retrieved successfully!")
else:
    print(f"Failed to retrieve products data. Status code: {get_products_data.status_code}")

Products retrieved successfully!

In [7]:
#get the raw products data as is
products_df_raw = pd.DataFrame(products_data)
print(products_df_raw.head())

#flatten the raw data to get a clean flat table(prevent dict in columns)
products_df = pd.json_normalize(products_df_raw['products'])
products_df.head()

                                            products  total  skip  limit
0  {'id': 1, 'title': 'Essence Mascara Lash Princ...    194     0     30
1  {'id': 2, 'title': 'Eyeshadow Palette with Mir...    194     0     30
2  {'id': 3, 'title': 'Powder Canister', 'descrip...    194     0     30
3  {'id': 4, 'title': 'Red Lipstick', 'descriptio...    194     0     30
4  {'id': 5, 'title': 'Red Nail Polish', 'descrip...    194     0     30

,id,title,description,category,price,discountPercentage,rating,stock,tags,brand,...,minimumOrderQuantity,images,thumbnail,dimensions.width,dimensions.height,dimensions.depth,meta.createdAt,meta.updatedAt,meta.barcode,meta.qrCode
0,1,Essence Mascara Lash Princess,The Essence Mascara Lash Princess is a popular...,beauty,9.99,10.48,2.56,99,"[beauty, mascara]",Essence,...,48,[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,15.14,13.08,22.99,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,5784719087687,https://cdn.dummyjson.com/public/qr-code.png
1,2,Eyeshadow Palette with Mirror,The Eyeshadow Palette with Mirror offers a ver...,beauty,19.99,18.19,2.86,34,"[beauty, eyeshadow]",Glamour Beauty,...,20,[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,9.26,22.47,27.67,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,9170275171413,https://cdn.dummyjson.com/public/qr-code.png
2,3,Powder Canister,The Powder Canister is a finely milled setting...,beauty,14.99,9.84,4.64,89,"[beauty, face powder]",Velvet Touch,...,22,[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,29.27,27.93,20.59,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,8418883906837,https://cdn.dummyjson.com/public/qr-code.png
3,4,Red Lipstick,The Red Lipstick is a classic and bold choice ...,beauty,12.99,12.16,4.36,91,"[beauty, lipstick]",Chic Cosmetics,...,40,[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,18.11,28.38,22.17,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,9467746727219,https://cdn.dummyjson.com/public/qr-code.png
4,5,Red Nail Polish,The Red Nail Polish offers a rich and glossy r...,beauty,8.99,11.44,4.32,79,"[beauty, nail polish]",Nail Couture,...,22,[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,21.63,16.48,29.84,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,4063010628104,https://cdn.dummyjson.com/public/qr-code.png

In [8]:
get_carts_data = requests.get(carts_url)

if get_carts_data.status_code == 200:
    #parse json data into a dictionary or list
    carts_data = get_carts_data.json()
    print("Cart data retrieved successfully!")
else:
    print(f"Failed to retrieve carts data. Status code: {get_carts_data.status_code}")

Cart data retrieved successfully!

In [10]:
#get the raw carts data as is
carts_df_raw = pd.DataFrame(carts_data)
print(carts_df_raw.head())

#flatten the raw data to get a clean flat table(prevent dict in columns)
carts_df = pd.json_normalize(carts_df_raw['carts'])
df_exploded = carts_df.explode('products').reset_index(drop=True)
products_normalized = pd.json_normalize(df_exploded['products'])
final_df = pd.concat([df_exploded.drop(columns=['products']), products_normalized], axis=1)
final_df.head()

                                               carts  total  skip  limit
0  {'id': 1, 'products': [{'id': 162, 'title': 'B...    208     0     30
1  {'id': 2, 'products': [{'id': 86, 'title': 'Ma...    208     0     30
2  {'id': 3, 'products': [{'id': 24, 'title': 'Fi...    208     0     30
3  {'id': 4, 'products': [{'id': 92, 'title': 'Sp...    208     0     30
4  {'id': 5, 'products': [{'id': 161, 'title': 'S...    208     0     30

,id,total,discountedTotal,userId,totalProducts,totalQuantity,id,title,price,quantity,total,discountPercentage,discountedTotal,thumbnail
0,1,13037.88,11510.81,1,4,12,162,Blue Frock,29.99,4,119.96,12.13,105.41,https://cdn.dummyjson.com/product-images/tops/...
1,1,13037.88,11510.81,1,4,12,113,Generic Motorcycle,3999.99,3,11999.97,12.10,10547.97,https://cdn.dummyjson.com/product-images/motor...
2,1,13037.88,11510.81,1,4,12,122,iPhone 6,299.99,3,899.97,6.69,839.76,https://cdn.dummyjson.com/product-images/smart...
3,1,13037.88,11510.81,1,4,12,138,Baseball Ball,8.99,2,17.98,1.71,17.67,https://cdn.dummyjson.com/product-images/sport...
4,2,139.93,125.70,2,2,7,86,Man Short Sleeve Shirt,19.99,5,99.95,6.83,93.12,https://cdn.dummyjson.com/product-images/mens-...

### Export data to csv

In [11]:
from pathlib import Path
output_dir = Path('data')
product_file_path = output_dir / 'product_data.csv'
cart_file_path = output_dir / 'cart_data.csv'

#create the output folder if it doesn't exist
output_dir.mkdir(parents=True, exist_ok=True)

In [12]:
#export to csv
products_df.to_csv(product_file_path,index=False)
carts_df.to_csv(cart_file_path,index=False)